### ISSUE TITLE
Use fixtures for storybook and jest snapshot

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#208]
Share fixtures file for each component between storybook and jest snapshots 

https://youtu.be/AkCeYUWncjk

**Comment by penx** [comment]
https://github.com/storybooks/storybook/tree/master/addons/storyshots

**Comment by penx** [comment]
Need to consider whether this is compatible with storybook addons such as knobs, or to have some fixtures that are storybook specific stay in storybook

**Comment by penx** [comment]
Mark did some work on this in #213, need to continue to do this in new PRs.

**Comment by penx** [comment]
I think:

- there shouldn't be any fixtures in stories.js or test.js
- all fixtures should be in fixtures.js
- all fixtures should be used by stories.js
- all fixtures should be used by test.js
- example.js should use the default export from fixtures.js and perhaps be deprecated

**Comment by stevesims** [comment]
We've since had second thoughts on this.

In reality, it's not as useful as we'd first thought to share fixtures between tests and stories.  Having fixtures in a separate file makes both tests and stories harder to understand when reviewing their code, as they are by definition not self-contained.  For unit tests at least this is against best practice.

Our create-component script has since been updated and will no longer generate separate a fixture file.

Closing
