### ISSUE TITLE
Passing a child prop inDateInput should be optional

### ISSUE THREAD

**Issue by hom-bahrani** [govuk-react/govuk-react#289]
I need to use this date input without the child prop

**Comment by stevesims** [comment]
I have a feeling that this may be down to the slight confusion we currently have between “input” and “field” components. Sorting this out is a priority

**Comment by penx** [comment]
Where we use the term 'Field', we intend to supply the label, hint text, error text and input all within one component, in a way that is easy to use with final-form.

Where the individual components are needed, you should use the underlying elements. In this case DateInput rather than DateField.

The problem here is that we are not exporting the DateInput or DateInputContainer.

I will export this on DateField.Input and DateField.Container for now, though form fields will have a more thorough review for consistency in #249.
