### ISSUE TITLE
Add props used for styling to their relevant rendered component

### ISSUE THREAD

**Issue by Loque-** [govuk-react/govuk-react#321]
**Problem:**
Components can accept props that will effect their visual appearance that are not documented.

**Example:**
Documentation: https://github.com/UKHomeOffice/govuk-react/tree/master/components/label
Available style prop: https://github.com/UKHomeOffice/govuk-react/blob/master/components/label/src/index.js#L21

**Proposed solution:**
Apply props used for style to their relevant component so the documentation tooling picks up on them, for the `Label` example;

```
const Label = ({ error, ...props }) => <StyledLabel error={error} {...props} />;

Label.propTypes = {
  /**
   * Apply error state styling to the component
   */
  error: PropTypes.bool,
};

Label.defaultProps = {
  error: false,
};
```

There could be a positive side effect to this also, which is that components can reveal their props without having to be visually inspected, although, I can't currently think of a situation where that is required other than snapshot tests.

Any thoughts?

**Comment by stevesims** [comment]
Yes - all props that affect styling should be documented, especially because this affects their generated documentation.

In this particular example it's an error (pun intended - sorry).

What's more of a problem is that most components now either directly, or indirectly, use the `withWhiteSpace` styling function and thus support `mb`, `margin`, and `padding` props.  Ideally the way you'd do this would be to do something like this:
```
Component.propTypes = {
  [regular definitions here],
  /**
   * Apply whitespace
   */
  ...spacing.withWhiteSpace.propTypes,
};
```
Technically this would work, and add the appropriate `propTypes` definitions for `withWhiteSpace` to `Component`, but unfortunately this is incompatible with the documentation generation system - those props don't get documented.

**Comment by stevesims** [comment]
Closing in favour of #577
