### ISSUE TITLE
Travis not publishing to npm 

### ISSUE THREAD

**Issue by Loque-** [govuk-react/govuk-react#418]
I'm not sure why but it seems that Travis did not publish to npm yesterday when following the release process.

To address this I manually ran the command in the travis.yml file off master, after the PR for the update had been merged in.

I am not sure on how travis kicks off the the npm publish or where to debug it, if someone can point me in the right direction I can have a look.

**Comment by stevesims** [comment]
The last travis build i can see (https://travis-ci.org/UKHomeOffice/govuk-react/builds/433031481) was for the pull request for v0.2.12.  The chromatic run in it is saying there are two changes.

The last travis build for master was just before that one (https://travis-ci.org/UKHomeOffice/govuk-react/builds/433030408).  Whilst the commit message indicates that it's for v0.2.12 the final item in the log says `Skipping a deployment with the script provider because this is not a tagged commit`.

So something about the release process meant that it didn't tag master before travis did it's build. ☹️

**Comment by Loque-** [comment]
Nice one - seems it might be an issue with travis (as other people have reported the same issue)[https://github.com/travis-ci/travis-ci/issues/9437]. I'll try and confirm it was tagged and try some solutions if it was.

**Comment by Loque-** [comment]
Is odd, travis can see it is tagged, and that it links to the PR; https://travis-ci.org/UKHomeOffice/govuk-react/builds/433031481

<img width="249" alt="screen shot 2018-09-27 at 11 13 15" src="https://user-images.githubusercontent.com/657572/46142650-8dae1080-c24f-11e8-99f7-d87521042a20.png">

I'll ask the one like the Alasdair tomorrow.

**Comment by stevesims** [comment]
Closing - I think this all got resolved, and recent changes have made the release process even more robust.
