### ISSUE TITLE
DateField type=number causing significant user issues

### ISSUE THREAD

**Issue by Joe-Brady** [govuk-react/govuk-react#481]
Quick bit of feedback from a recent change to the `DateField` component - by making the input fields `type=number`, all browsers with HTML5 support add their own version of little ‘up/down’ arrows.

There are two issues with this - firstly, while Chrome makes the arrows nice and small, Firefox and Safari etc. are less elegant and can actually obscure the numbers that users enter.

Second issue is pretty major for our service - people consistently started clicking on the arrows rather than typing into the fields, which immediately caused a lot of grumbling that “It takes ages to select the correct date, and how am I supposed to get it to 2018 in the year field?!“, which is surprising but true across a wide variety of users.

I have temporarily circumvented the issue with this CSS suggestion: https://www.thatstevensguy.com/programming/disable-arrows-on-number-inputs/

![screen shot 2018-11-29 at 10 47 43](https://user-images.githubusercontent.com/20062773/49216974-4c0f2280-f3c4-11e8-8700-4e0fa318fb41.png)

![screen shot 2018-11-29 at 10 46 16](https://user-images.githubusercontent.com/20062773/49216973-4c0f2280-f3c4-11e8-90ad-ef58d658b916.png)

**Comment by penx** [comment]
Open to a PR to disable this for now.

We should be mirroring what the govuk-frontend templates do. They do use type=number but I guess they are working around the issue you describe in a similar way.

https://github.com/alphagov/govuk-frontend/blob/master/src/components/date-input/template.njk

**Comment by penx** [comment]
I would have thought govuk-frontend has already resolved this issue so we should be mirroring what they do unless (a) they haven't resolved the issue or (b) something prevents us from mirroring their css/markup.

Happy to remove type=number short term. If a or b then yes lets remove type=number long term.

I should also mention that you can roll back to an old version of a specific component.

e.g. for DateField


```
import { H1, Paragraph } from 'govuk-react';
import DateField from '@govuk-react/date-field';
```

Then in your package.json, specify an older version of `'@govuk-react/date-field'`.

This is by design, to allow users to always update to the latest version of govuk-react but to roll back specific components if there are breaking changes they don't want. It's the main reason govuk-react is a monorepo.

**Comment by Joe-Brady** [comment]
Thanks for the tip on rolling back! Hadn't clocked that
