### ISSUE TITLE
Flatten storybook

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#632]
I really don't like our component categorisation in storybook
I'm like
> I made this repo

but yet

> I have no idea where to find this thing I'm looking for

it starts to make a bit more sense when you start clicking around
but I'd massively prefer a flat list

I think users are gonna be more like

> what components are available

or

> where is component X

rather than

> what components are available in this category

would love thoughts from users on this :-) @Djangofs @jsrobertson

**Comment by jsrobertson** [comment]
I think a flat list could work or even a components section at least which matches up to the [govuk design system](https://design-system.service.gov.uk/components/character-count/)? 

I do use the filter in the top left pretty much every time I use the govuk-react storybook though.

**Comment by dsm23** [comment]
I've been thinking. May it be viable to include all our components grouped in a components tab and then another tab for examples of how tot replicate the patterns in https://design-system.service.gov.uk/patterns/. However, I know how devoid of content the storybook would look on load with only two closed tabs.

**Comment by stevesims** [comment]
Quick dump of my thoughts on this, based on messages I'd earlier sent to @penx on slack...

I hear ya - and do agree - to an extent.

I'm not convinced by a completely flat list tho.  The "Components" page of the GDS site is OK - but at 27 items I'd say they're at about the limit of the number of components a flat list can work for.

On the other hand, we currently have 54 components each with separate entries in storybook, plus another 9 stories covering icons, some HOCs, and the root readme.

We have (over) twice the number of components they do mostly because there are parts of govuk-frontend that are "components" in our world, but are instead simple "styles" in theirs, and are illustrated under sub-sections of "styles" on their site ("layout", "spacing" and "typography") - and some parts that they do not directly illustrate at all.

Given that we have so many more components, it feels to me that some degree of classification is needed to make the list in storybook manageable.  What's clear is our current classification however doesn't quite work.  We should look to simplify it.

In order to help make the storybook more navigable we may also wish to look into place stories under multiple parts of the tree.  For example, if we had top-level categories of "Layout" and "Navigation", we may wish to place the "Tabs" component under both of those.

I'd also note that if we change our classification that may be a sensible time to also address #589

**Comment by Loque-** [comment]
I don't think a flat list will help, the search feature is also really good in storybook.

Better categorisation might work, but it takes time to rationalise the components into clean groups... for example `Data`, `Tabs` and `Misc` could do with further thought.

If there was some way of incorporating atomic design folder structure principles ontop, I'd be super happy too, this also touches on how closely the repo needs to stick to existing GDS stuff tho.
