### ISSUE TITLE
Console warning in top-nav

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#652]
The top-nav component causes a console warning owing to the use of the `checked` prop on a checkbox input element.

We should investigate this to see if there's a way to remove the warning.

**Comment by Protonull** [comment]
Sorry for necroposting. I've been looking into this and it's caused by [this component](https://github.com/govuk-react/govuk-react/blob/master/components/top-nav/src/index.js#L160) in the top-nav, which is then modified externally by [this component](https://github.com/govuk-react/govuk-react/blob/master/components/top-nav/src/atoms/menu-button/index.js#L39). I'm unsure if the menu-button's onClick handler would satisfy the input's desire for an onChange handler if it were inline.
