### ISSUE TITLE
Details component show/hide is not working on Ie11

### ISSUE THREAD

**Issue by EduardoSolanas** [govuk-react/govuk-react#715]
Hello,

I just started using your react library for a gov uk project.
I am testing some pages that use Details component and I just realised that in IE11 the show and hide summary link is not working on IE11, it works for Chrome etc.

I tried both leaving it as default and also setting the open to close but nothing worked, it seems like the on click is doing nothing at all, no console errors anything

Another note is while testing it on with react-testing lib, it seems that they also are kept open, maybe is the way how you are hiding/showing the content, because you are not using display none, react-test always detects the content like visible, this could be the problem also for IE11, using display: none seems to be a reasonable fix maybe? I also checked the source code and there is no test for the show/hide funcionality

Thanks

**Comment by stevesims** [comment]
Unfortunately IE11 has no support for the HTML5 `details` element. You will indeed not see any errors in the console - it's just not supported.  Fortunately, IIRC, the behaviour it exhibits is just that the revealed content is shown.

We didn't write tests for show/hide functionality because we are relying on the default browser behaviour.  For us when we first wrote this it wasn't important to have full compatibility with IE11 for the `Details` component - the fallback default functionality of "content is shown" was acceptable.

If There is a polyfill available which may help: https://github.com/rstacruz/details-polyfill
I have not investigated it's use - that repo also links to several other polyfill modules.

**Comment by EduardoSolanas** [comment]
I see that makes sense, sorry for the inconveniences, I will play with the polyfills thanks!

**Comment by stevesims** [comment]
No inconvenience at all.  :grin:

This issue has actually been raised before #699 so the lesson is that we should have done a better job of messaging the advice about using a polyfill.

Please let us know how you get on.

A PR to update the documentation for the Details component would of course also be very gratefully received. 😀
