### ISSUE TITLE
Implement lerna-alias and update readme (was: Improve monorepo and storybook integration)

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#93]
e.g. live reloading, compilation issues

https://github.com/julianburr/storybook-monorepo-concept

**Comment by penx** [comment]
Could use #107 but likely want better debugging output than that will provide

**Comment by penx** [comment]
@stevesims @marksy please let me know how you get on with storybook development with the watch and monorepo structure, are there any oddities? Do you see the correct source maps for all code/components you're working on in the Chrome debugger? Is anything worse than it was before?

**Comment by marksy** [comment]
One issue i've just realised is the watcher isn't building the exported component. E.g.
1. i'm building an HoC and the story file imports each of the (standard) components in.
2. when i need to modify one of the (standard) components, the watcher runs and compiles to lib folder (which works as expected)
3. on Storybook my HoC's story (of the modified component as discussed in point 2) doesnt update, even after manual refresh.
4. to get the component to update, i need to run a manual `yarn build`

is this because the watcher/build task doesn't output the recently modified component to the ES folder?

This is a rare occurrence, because it's not often this development approach would be used.

**Comment by marksy** [comment]
Ranked annoyances
1. `yarn build`. It does way too much for a build (83 sec on my MBP, 120 on my work MBA). IMO this should build components that don't have `es` or `lib`  rather than do a clean and build-all. Perhaps there should be a separate `yarn clean`, and a `yarn production` which does a clean first, then build.

_I guess you will need to rimraf the `es` & `lib` folders when you checkout a branch anyway..._

2. `yarn watch`. I dont know how reliable this task is. Only existing components are watched, and only in the Components folder. This task doesnt watch components in Packages. Sometimes i kill the watch task because it hasnt updated chrome. Mostly i will resort to `yarn build` again and then rerun `yarn watch`

3. Having multiple bash windows open to run similar tasks. Is it possible to have it build, serve and watch all in one window? CRA does this, no?

**Comment by marksy** [comment]
4. when `yarn watch`, if you accidentally break the build by forgetting to insert a comma and then saving, the watch doesnt resume after you correct the issue

**Comment by penx** [comment]
> One issue i've just realised is the watcher isn't building the exported component

PR #211 should hopefully have resolved these

> 2. yarn watch, 4. when yarn watch

shouldn't need yarn watch anymore so redundant

> 1. yarn build

shouldn't need to yarn build locally now as yarn start will launch storybook which will do everything we need (other than `yarn` on its own to install dependencies and set up monorepo)

**Comment by penx** [comment]
@marksy please let me know if any of the above are still an issue (post #211) other than having multiple bash windows open

**Comment by marksy** [comment]
What you have done is :thumb:

but, 3+ sec feels real slow. 

In the mean time, while we are we are awaiting optimisation, can we have [some sort of alert](https://www.npmjs.com/package/node-notifier) to say it's finished

**Comment by marksy** [comment]
although that _may_ get annoying to _some_ people

**Comment by marksy** [comment]
btw - running a `yarn test:snapshot` requires the project to be built first using `yarn build`

**Comment by penx** [comment]
> btw - running a yarn test:snapshot requires the project to be built first using yarn build

ah right, for sub dependencies yes, because jest doesn't have the webpack alias to src that I set up.

Can't think of a solution for that right now 🙁

**Comment by penx** [comment]
as suggested by mitchellhamilton on Emotion Slack - https://github.com/Andarist/lerna-alias

**Comment by penx** [comment]
I think the only remaining issues here are:

- use lerna-alias
- ensure readme/contributing describes development practices that don't result in above pain points

So will rename this ticket
